/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2022 Ben Vanik. All rights reserved.                             *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 */

#ifndef XENIA_GPU_COMMAND_PROCESSOR_H_
#define XENIA_GPU_COMMAND_PROCESSOR_H_

#include <algorithm>
#include <atomic>
#include <cstring>
#include <deque>
#include <functional>
#include <memory>
#include <mutex>
#include <queue>
#include <string>
#include <unordered_map>
#include <vector>

#include "xenia/base/math.h"
#include "xenia/base/ring_buffer.h"
#include "xenia/gpu/register_file.h"
#include "xenia/gpu/trace_writer.h"
#include "xenia/gpu/xenos.h"
#include "xenia/gpu/xenos_report_controller.h"
#include "xenia/gpu/xenos_zpd_report.h"
#include "xenia/kernel/xthread.h"
#include "xenia/memory.h"
#include "xenia/ui/presenter.h"

namespace xe {

class ByteStream;

namespace gpu {

enum class GPUSetting {
  ClearMemoryPageState,
  ReadbackMemexport,
  ReadbackMemexportFast
};

enum class ReadbackResolveMode {
  kDisabled,  // No readback (none)
  kSome,      // Delayed sync, skip copy on cache hit (some)
  kFast,      // Delayed sync, copy every frame (fast)
  kFull       // Immediate sync with GPU stall (full)
};

void SaveGPUSetting(GPUSetting setting, uint64_t value);
bool GetGPUSetting(GPUSetting setting);

// ZPD query resolves are always 64-bit sample counts.
constexpr uint32_t kHostZPDResolveStrideBytes = 8;

// Clamps the pool size and rounds it up for bitmask wrapping.
inline uint32_t GetClampedHostZPDPoolCapacity(int32_t capacity) {
  static constexpr int32_t kHostZPDPoolCapacityMin = 16;
  static constexpr int32_t kHostZPDPoolCapacityMax = 524288;
  uint32_t requested_capacity = static_cast<uint32_t>(
      std::clamp(capacity, kHostZPDPoolCapacityMin, kHostZPDPoolCapacityMax));
  return xe::next_pow2(requested_capacity);
}

class GraphicsSystem;
class Shader;

struct SwapState {
  // Lock must be held when changing data in this structure.
  std::mutex mutex;
  // Dimensions of the framebuffer textures. Should match window size.
  uint32_t width = 0;
  uint32_t height = 0;
  // Current front buffer, being drawn to the screen.
  uintptr_t front_buffer_texture = 0;
  // Current back buffer, being updated by the CP.
  uintptr_t back_buffer_texture = 0;
  // Backend data
  void* backend_data = nullptr;
  // Whether the back buffer is dirty and a swap is pending.
  bool pending = false;
};

enum class SwapMode {
  kNormal,
  kIgnored,
};

enum class GammaRampType {
  kUnknown = 0,
  kTable,
  kPWL,
};

class CommandProcessor {
 protected:
  RingBuffer
      reader_;  // chrispy: instead of having ringbuffer on stack, have it near
                // the start of the class so we can access it via rel8. This
                // also reduces the number of params we need to pass
 public:
  enum class SwapPostEffect {
    kNone,
    kFxaa,
    kFxaaExtreme,
  };

  CommandProcessor(GraphicsSystem* graphics_system,
                   kernel::KernelState* kernel_state);
  virtual ~CommandProcessor();
  uint32_t counter() const { return counter_; }
  void increment_counter() { counter_++; }

  Shader* active_vertex_shader() const { return active_vertex_shader_; }
  Shader* active_pixel_shader() const { return active_pixel_shader_; }

  virtual bool Initialize();
  virtual void Shutdown();

  void CallInThread(std::function<void()> fn);

  virtual void ClearCaches();
  virtual void InvalidateGpuMemory();
  virtual void ClearReadbackBuffers();

  // Get cached readback resolve mode (avoids string parsing every frame)
  ReadbackResolveMode GetReadbackResolveMode() const {
    return cached_readback_resolve_mode_;
  }

  // Set readback resolve mode (updates both cvar and cached value)
  void SetReadbackResolveMode(ReadbackResolveMode mode);

  // "Desired" is for the external thread managing the post-processing effect.
  SwapPostEffect GetDesiredSwapPostEffect() const {
    return swap_post_effect_desired_;
  }
  void SetDesiredSwapPostEffect(SwapPostEffect swap_post_effect);
  // Implementations must not make assumptions that the front buffer will
  // necessarily be a resolve destination - it may be a texture generated by any
  // means like written to by the CPU or loaded from a file (the disclaimer
  // screen right in the beginning of 4D530AA4 is not a resolved render target,
  // for instance).
  virtual void IssueSwap(uint32_t frontbuffer_ptr, uint32_t frontbuffer_width,
                         uint32_t frontbuffer_height) {}

  // Throttle presentation based on framerate_limit cvar.
  // Called after IssueSwap to limit host frame rate without affecting guest
  // vblank timing.
  void ThrottlePresentation();

  // May be called not only from the command processor thread when the command
  // processor is paused, and the termination of this function may be explicitly
  // awaited.
  virtual void InitializeShaderStorage(
      const std::filesystem::path& cache_root, uint32_t title_id, bool blocking,
      std::function<void()> completion_callback = nullptr);

  virtual void RequestFrameTrace(const std::filesystem::path& root_path);
  virtual void BeginTracing(const std::filesystem::path& root_path);
  virtual void EndTracing();

  virtual void TracePlaybackWroteMemory(uint32_t base_ptr, uint32_t length) = 0;

  void RestoreRegisters(uint32_t first_register,
                        const uint32_t* register_values,
                        uint32_t register_count, bool execute_callbacks);
  void RestoreGammaRamp(
      const reg::DC_LUT_30_COLOR* new_gamma_ramp_256_entry_table,
      const reg::DC_LUT_PWL_DATA* new_gamma_ramp_pwl_rgb,
      uint32_t new_gamma_ramp_rw_component);
  virtual void RestoreEdramSnapshot(const void* snapshot) = 0;

  void InitializeRingBuffer(uint32_t ptr, uint32_t size_log2);
  void EnableReadPointerWriteBack(uint32_t ptr, uint32_t block_size_log2);

  void UpdateWritePointer(uint32_t value);

  void LogRegisterSet(uint32_t register_index, uint32_t value);
  void LogRegisterSets(uint32_t base_register_index, const uint32_t* values,
                       uint32_t n_values);

  bool is_paused() const { return paused_; }
  void Pause();
  void Resume();

  bool Save(ByteStream* stream);
  bool Restore(ByteStream* stream);

 protected:
  struct IndexBufferInfo {
    xenos::IndexFormat format = xenos::IndexFormat::kInt16;
    xenos::Endian endianness = xenos::Endian::kNone;
    uint32_t count = 0;
    uint32_t guest_base = 0;
    size_t length = 0;
  };

  static constexpr uint32_t kReadbackBufferSizeIncrement = 16 * 1024 * 1024;

  // Eviction policy constants for readback buffer cache
  static constexpr size_t kMaxReadbackBuffers = 256;
  static constexpr uint64_t kReadbackBufferEvictionAgeFrames = 60;

  // Progressive alignment for readback buffers to avoid wasting memory
  static inline uint32_t AlignReadbackBufferSize(uint32_t size) {
    if (size < 1 * 1024 * 1024) {
      return xe::align(size, 256u * 1024u);  // 256KB for < 1MB
    } else if (size < 4 * 1024 * 1024) {
      return xe::align(size, 1u * 1024u * 1024u);  // 1MB for < 4MB
    } else {
      return xe::align(size, kReadbackBufferSizeIncrement);  // 16MB for >= 4MB
    }
  }

  // Generate a cache key for a specific resolve operation
  static inline uint64_t MakeReadbackResolveKey(uint32_t address,
                                                uint32_t length) {
    return (uint64_t(address) << 32) | uint64_t(length);
  }

  void WorkerThreadMain();
  virtual bool SetupContext() = 0;
  virtual void ShutdownContext() = 0;
  // rarely needed, most register writes have no special logic here
  XE_NOINLINE
  void HandleSpecialRegisterWrite(uint32_t index, uint32_t value);

  virtual void WriteRegister(uint32_t index, uint32_t value);

  // mem has big-endian register values
  XE_FORCEINLINE
  virtual void WriteRegistersFromMem(uint32_t start_index, uint32_t* base,
                                     uint32_t num_registers);

  XE_FORCEINLINE
  virtual void WriteRegisterRangeFromRing(xe::RingBuffer* ring, uint32_t base,
                                          uint32_t num_registers);

  XE_NOINLINE
  void WriteOneRegisterFromRing(
      uint32_t base,
      uint32_t
          num_times);  // repeatedly write a value to one register, presumably a
                       // register with special handling for writes

  void WriteALURangeFromRing(xe::RingBuffer* ring, uint32_t base,
                             uint32_t num_times);

  void WriteFetchRangeFromRing(xe::RingBuffer* ring, uint32_t base,
                               uint32_t num_times);

  void WriteBoolRangeFromRing(xe::RingBuffer* ring, uint32_t base,
                              uint32_t num_times);

  void WriteLoopRangeFromRing(xe::RingBuffer* ring, uint32_t base,
                              uint32_t num_times);

  void WriteREGISTERSRangeFromRing(xe::RingBuffer* ring, uint32_t base,
                                   uint32_t num_times);

  void WriteALURangeFromMem(uint32_t start_index, uint32_t* base,
                            uint32_t num_registers);

  void WriteFetchRangeFromMem(uint32_t start_index, uint32_t* base,
                              uint32_t num_registers);

  void WriteBoolRangeFromMem(uint32_t start_index, uint32_t* base,
                             uint32_t num_registers);

  void WriteLoopRangeFromMem(uint32_t start_index, uint32_t* base,
                             uint32_t num_registers);

  void WriteREGISTERSRangeFromMem(uint32_t start_index, uint32_t* base,
                                  uint32_t num_registers);

  const reg::DC_LUT_30_COLOR* gamma_ramp_256_entry_table() const {
    return gamma_ramp_256_entry_table_;
  }
  const reg::DC_LUT_PWL_DATA* gamma_ramp_pwl_rgb() const {
    return gamma_ramp_pwl_rgb_[0];
  }
  virtual void OnGammaRamp256EntryTableValueWritten() {}
  virtual void OnGammaRampPWLValueWritten() {}

  virtual void MakeCoherent();
  virtual void PrepareForWait();
  virtual void ReturnFromWait();

  virtual void OnPrimaryBufferEnd() {}

  // ZPD report handling lives here.
  //
  // In this code, "report" means the 360 memory record, and "query" means the
  // API object that produces the sample count.
  //
  // Backends own the pool and submission side. This class owns the logical
  // lifetime and the writeback flow.
  enum class HostZPDQueryOpenResult {
    kOpened,         // Opened successfully.
    kDeferred,       // Delayed for now.
    kPoolExhausted,  // Pool is out of queries.
    kFailed,         // Open failed.
  };

  // One logical ZPD report.
  struct LogicalGuestZPDReport {
    uint32_t begin_report_address = 0;
    uint32_t begin_record = 0;
    uint32_t end_record = 0;
    uint64_t accumulated_samples = 0;
    uint64_t last_segment_end_submission = 0;
    uint32_t pending_segments = 0;
    bool ended = false;
  };

  // One active query segment for a logical ZPD report.
  struct ActiveHostZPDQuerySegment {
    XenosReportController::ReportHandle report_handle =
        XenosReportController::kInvalidReportHandle;
    uint32_t begin_report_address = 0;
    uint32_t begin_record = 0;
    uint32_t end_report_address = 0;
    uint32_t query_index = UINT32_MAX;
    uint32_t query_generation = 0;
    bool segment_active = false;
    bool segment_pending_begin = false;
    bool logical_active = false;
  };

  // Pending resolve for retired query segments.
  struct PendingHostZPDQueryResolve {
    uint64_t submission = 0;
    uint32_t query_index = UINT32_MAX;
    uint32_t query_generation = 0;
    XenosReportController::ReportHandle report_handle =
        XenosReportController::kInvalidReportHandle;
  };

  // Guest ZPD report counters. Logged by the backend every 100 frames.
  struct GuestZPDReportStats {
    uint64_t logical_begun = 0;
    uint64_t logical_ended = 0;
    uint64_t segments_begun = 0;
    uint64_t segments_ended = 0;
    uint64_t resolves_completed = 0;
    uint64_t resolves_discarded_stale = 0;
    uint64_t pool_exhausted = 0;
    uint64_t failed = 0;
    uint64_t last_log_frame = 0;
  };

  // Query resources.
  virtual void EnsureZPDHostQueryResources() {}
  virtual void ShutdownZPDHostQueryResources() {}
  virtual bool IsHostZPDQueryPoolReady() const { return false; }
  virtual bool CanOpenHostZPDQueryNow() const { return true; }
  // Opens a query.
  virtual HostZPDQueryOpenResult OpenHostZPDQuery(uint32_t& out_host_index,
                                                  uint32_t& out_host_generation,
                                                  bool can_close_submission) {
    return HostZPDQueryOpenResult::kFailed;
  }
  // Closes a query and returns the submission it lands on.
  virtual bool CloseHostZPDQuery(uint32_t host_index, uint32_t host_generation,
                                 uint64_t& out_submission) {
    return false;
  }
  virtual uint64_t GetHostZPDQueryResult(uint32_t host_index) { return 0; }
  virtual void ReleaseHostZPDQuery(uint32_t host_index,
                                   uint32_t host_generation) {}
  // Checks the generation before using the result.
  virtual bool IsHostZPDQueryResultValid(uint32_t host_index,
                                         uint32_t host_generation) const {
    return true;
  }

  // Submission and readback.
  // Prepares completed resolves for readback.
  virtual void PrepareHostZPDReadback(uint64_t completed_submission,
                                      uint64_t settle_margin) {}
  virtual bool ShouldDropHostZPDReportIfUnavailable() const { return false; }
  virtual uint64_t GetHostZPDCurrentSubmission() const { return 0; }
  virtual uint64_t GetHostZPDCompletedSubmission() const { return 0; }
  virtual void AwaitHostZPDSubmissionAndUpdateCompleted(uint64_t submission) {}
  virtual bool CanEndHostZPDSubmissionImmediately() const { return false; }
  virtual bool EndHostZPDSubmission(bool is_swap) { return false; }
  virtual void PrepareToWaitForHostZPDSubmission() {}
  virtual uint32_t GetZPDReportDrawResolutionScaleX() const { return 1; }
  virtual uint32_t GetZPDReportDrawResolutionScaleY() const { return 1; }

  // Logical report state.
  bool BeginGuestZPDReport(uint32_t report_address);
  bool EndGuestZPDReport(uint32_t report_address, bool guest_forced_end);
  void ResumeActiveHostZPDQuerySegment(bool can_close_submission);
  void SplitActiveHostZPDQuerySegment();
  void ProcessCompletedHostZPDQueryResolves(uint64_t completed_submission);
  void CommitGuestZPDReportData(uint32_t begin_record,
                                uint32_t report_record_base,
                                uint32_t delta_value, bool write_begin_record);
  bool IsFastZPDPathEnabled() const;
  // Applies draw resolution scaling before the final write.
  uint32_t NormalizeZPDReportSampleCount(uint64_t samples) const;
  // Controller callback for writes that can retire now.
  static void CommitGuestZPDReportCallback(
      XenosReportController::ReportHandle report_handle,
      uint32_t report_record_base, uint32_t delta_value,
      bool write_begin_report, void* callback_context);
  // Controller callback for writes that still need more progress.
  static void WaitAndResolveZPDReportCallback(
      XenosReportController::ReportHandle report_handle,
      void* callback_context);

#include "pm4_command_processor_declare.h"

  virtual Shader* LoadShader(xenos::ShaderType shader_type,
                             uint32_t guest_address,
                             const uint32_t* host_address,
                             uint32_t dword_count) {
    return nullptr;
  }

  virtual bool IssueDraw(xenos::PrimitiveType prim_type, uint32_t index_count,
                         IndexBufferInfo* index_buffer_info,
                         bool major_mode_explicit) {
    return false;
  }
  virtual bool IssueCopy() { return false; }

  // Debug marker stubs for base class (overridden by D3D12/Vulkan backends).
  bool debug_markers_enabled() const { return false; }
  void PushDebugMarker(const char* format, ...) {}
  void PopDebugMarker() {}
  void InsertDebugMarker(const char* format, ...) {}

  // "Actual" is for the command processor thread, to be read by the
  // implementations.
  SwapPostEffect GetActualSwapPostEffect() const {
    return swap_post_effect_actual_;
  }

  virtual void InitializeTrace();

  Memory* memory_ = nullptr;
  kernel::KernelState* kernel_state_ = nullptr;
  GraphicsSystem* graphics_system_ = nullptr;
  RegisterFile* XE_RESTRICT register_file_ = nullptr;

  mutable std::mutex zpd_report_mutex_;
  std::unique_ptr<XenosReportController> zpd_report_controller_;
  std::unordered_map<XenosReportController::ReportHandle, LogicalGuestZPDReport>
      logical_zpd_reports_;
  ActiveHostZPDQuerySegment active_host_zpd_query_segment_{};
  std::deque<PendingHostZPDQueryResolve> host_zpd_query_resolves_in_flight_;

  // Cached END delta for the fast path until the real resolve is ready.
  // Keyed by record base.
  std::unordered_map<uint32_t, uint32_t> fast_zpd_report_cached_values_;

  // Rolling count for the no-hardware path.
  uint32_t fake_zpd_sample_count_ = 0;
  GuestZPDReportStats guest_zpd_report_stats_;

  TraceWriter trace_writer_;
  enum class TraceState {
    kDisabled,
    kStreaming,
    kSingleFrame,
  };
  TraceState trace_state_ = TraceState::kDisabled;
  std::filesystem::path trace_stream_path_;
  std::filesystem::path trace_frame_path_;

  std::atomic<bool> worker_running_;
  kernel::object_ref<kernel::XHostThread> worker_thread_;

  std::queue<std::function<void()>> pending_fns_;

  // MicroEngine binary from PM4_ME_INIT
  std::vector<uint32_t> me_bin_;

  uint32_t counter_ = 0;

  uint32_t primary_buffer_ptr_ = 0;
  uint32_t primary_buffer_size_ = 0;

  uint32_t read_ptr_index_ = 0;
  uint32_t read_ptr_update_freq_ = 0;
  uint32_t read_ptr_writeback_ptr_ = 0;

  std::unique_ptr<xe::threading::Event> write_ptr_index_event_;
  std::atomic<uint32_t> write_ptr_index_;

  uint64_t bin_select_ = 0xFFFFFFFFull;
  uint64_t bin_mask_ = 0xFFFFFFFFull;

  Shader* active_vertex_shader_ = nullptr;
  Shader* active_pixel_shader_ = nullptr;

  bool paused_ = false;

  // By default (such as for tools), post-processing is disabled.
  // "Desired" is for the external thread managing the post-processing effect.
  SwapPostEffect swap_post_effect_desired_ = SwapPostEffect::kNone;
  SwapPostEffect swap_post_effect_actual_ = SwapPostEffect::kNone;

  // Cached readback resolve mode (parsed once from string cvar)
  ReadbackResolveMode cached_readback_resolve_mode_ =
      ReadbackResolveMode::kFast;

  // For host frame rate limiting at IssueSwap
  uint64_t last_swap_time_ = 0;

 private:
  reg::DC_LUT_30_COLOR gamma_ramp_256_entry_table_[256] = {};
  reg::DC_LUT_PWL_DATA gamma_ramp_pwl_rgb_[128][3] = {};
  uint32_t gamma_ramp_rw_component_ = 0;

  XE_NOINLINE XE_COLD void LogKickoffInitator(uint32_t value);
};

}  // namespace gpu
}  // namespace xe

#endif  // XENIA_GPU_COMMAND_PROCESSOR_H_
